### ISSUE TITLE
BUILD_VALIDATOR_EVENT class constant

### ISSUE THREAD

**Issue by andrej-griniuk** [UseMuffin/Webservice#47] opened 2017-10-26 12:12 UTC
In CakePHP 3.5 classes using `ValidatorAwareTrait` must have `BUILD_VALIDATOR_EVENT` constant defined. In this case `Muffin\Webservice\Model\Endpoint` class. Currently causing "Undefined class constant 'BUILD_VALIDATOR_EVENT'" exception.

**Comment by ADmad** [comment] 2017-10-26 12:14
Duplicate of #46.

**Closed by ADmad** 2017-10-26 12:14 UTC
